#!/usr/bin/env bash                                                                                                                                       
# nginx listening on port 80 to be fixed                                                                        
# Go to sites-enabled folder for Nginx                                                                                                                  
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                            
#Erace the default file                                                                                                                 
rm default;                                                                                                                                   
# Create symlink to the deafult file in sites-available                                                            
ln -s /etc/nginx/sites-available/default default;                                              
# Restarting Nginx                                                                                                                                        
service nginx restart
